### ISSUE TITLE
The loop Button do not work

### ISSUE THREAD

**Issue by PiraHzq** [jplayer/react-jPlayer#1] opened 2017-07-05 08:30 UTC
Mac OS X 10.11.6
Chrome 59.0.3071.115
audio.loop = false
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

**Comment by apaschenko-amplify** [comment] 2017-07-25 12:51
Think the problem is that media component [tries to pause](https://github.com/jplayer/react-jPlayer/blob/master/src/components/media/mediaContainer.jsx#L242) audio/video that has already been paused.
Would be great to fix it.

**Comment by MartinDawson** [comment] 2017-07-25 13:19
@PiraHzq @apaschenko-amplify  I'll look at it tonight and hopefully fix it. I'v been busy with other projects but should be back on this soon. Quite a few things I want to add.

**Comment by MartinDawson** [comment] 2017-07-28 10:06
@PiraHzq 
@apaschenko-amplify Was pretty much correct.

Fixed in [5.0.3](https://github.com/jplayer/react-jPlayer/commit/6eb0dd746a36f1525c1a1cc3376bb5b1a8f8c9c6).

Try testing it now.

**Comment by MartinDawson** [comment] 2017-08-09 19:59
Opened again due to breaking react-jPlaylist functionality. Needs a proper fix asap.

**Comment by MartinDawson** [comment] 2017-09-10 15:49
@PiraHzq @apaschenko-amplify Works in v6. That play request error can just be ignored.

**Closed as completed by MartinDawson** 2017-09-10 15:49 UTC
Labels: bug
